spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/davinas
    username: postgres
    password: ymcmbysl22
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
