# application.yml (shared configuration)
spring:
  application:
    name: hotel-infrastructure
  profiles:
    active: dev

cloudflare:
  r2:
    accessKey: f3a36c5b5f59059ed8f21011de98aad0
    secretKey: 66af574f90f6ed63c0a78404ec632d96fdbefe5d1c00d4af516f33d34047b6a7
    bucketName: ikanetapps
    region: us-east-1
    endpoint: https://6494d232b86293b94c31271ae702822e.r2.cloudflarestorage.com
    storageDirectory: davina
    publicAccess: https://storage.ikanetapps.com

server:
  port: 9090
debug: true

logging:
  level:
    org.springframework.core.env: debug
    web: debug
    sql: debug
